# Generated by Django 5.1.5 on 2025-02-06 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_delete_product_alter_user_mobile_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='User-Profile'),
        ),
    ]
