# Generated by Django 5.1.5 on 2025-02-18 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0003_order_shipping_carrier_order_tracking_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='session_id',
            field=models.CharField(blank=True, null=True),
        ),
    ]
