# Generated by Django 5.1.5 on 2025-02-18 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0008_rename_status_order_status_check'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='status_check',
            new_name='status',
        ),
    ]
