# Generated by Django 5.1.5 on 2025-02-20 12:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0012_shippingcarrier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='shipping_carrier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='ecommerce.shippingcarrier'),
        ),
    ]
